// <auto-generated />
using System;
using CozaStore.Data.EntityContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CozaStore.Data.Migrations
{
    [DbContext(typeof(CozaStoreContext))]
    partial class CozaStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.CategoryEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnName("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orders")
                        .HasColumnName("Orders")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnName("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Collections Woman",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Collections Man",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Collections Children",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.ContactEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactTitle")
                        .IsRequired()
                        .HasColumnName("ContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnName("FullName")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("Message")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnName("PhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactTitle = "Tư Vấn",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqcuong720@gmail.com",
                            FullName = "Nguyễn Quốc Cường",
                            Message = "Yêu cầu cửa hàng thêm quần áo",
                            PhoneNumber = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ContactTitle = "Phản Hồi",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqcuong720@gmail.com",
                            FullName = "Nguyễn Quốc Khánh",
                            Message = "Yêu cầu cửa hàng thêm quần áo",
                            PhoneNumber = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ContactTitle = "Khiển Trách",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqcuong720@gmail.com",
                            FullName = "Nguyễn Quốc Duy",
                            Message = "Yêu cầu cửa hàng thêm quần áo",
                            PhoneNumber = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.OrderDetailEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnName("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnName("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnName("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 1,
                            Price = 45000000m,
                            ProductId = 1,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 2,
                            Price = 45000000m,
                            ProductId = 3,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 45000000m,
                            ProductId = 4,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 3,
                            Price = 45000000m,
                            ProductId = 2,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 4,
                            Price = 45000000m,
                            ProductId = 5,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 5,
                            Price = 45000000m,
                            ProductId = 4,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = 6,
                            Price = 45000000m,
                            ProductId = 12,
                            Quantity = 2,
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.OrderEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnName("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnName("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAdsress")
                        .IsRequired()
                        .HasColumnName("ShipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipEmail")
                        .IsRequired()
                        .HasColumnName("ShipEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipPhone")
                        .IsRequired()
                        .HasColumnName("ShipPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "None",
                            OrderDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipAdsress = "351A Lạc Long Quân P5 Quận 11 TP.Hồ Chí Minh",
                            ShipEmail = "nqcuong720@gmail.com",
                            ShipPhone = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "None",
                            OrderDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipAdsress = "351A Lạc Long Quân P5 Quận 11 TP.Hồ Chí Minh",
                            ShipEmail = "nqcuong720@gmail.com",
                            ShipPhone = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "None",
                            OrderDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipAdsress = "351A Lạc Long Quân P5 Quận 11 TP.Hồ Chí Minh",
                            ShipEmail = "nqcuong720@gmail.com",
                            ShipPhone = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "None",
                            OrderDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipAdsress = "351A Lạc Long Quân P5 Quận 11 TP.Hồ Chí Minh",
                            ShipEmail = "nqcuong720@gmail.com",
                            ShipPhone = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "None",
                            OrderDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipAdsress = "351A Lạc Long Quân P5 Quận 11 TP.Hồ Chí Minh",
                            ShipEmail = "nqcuong720@gmail.com",
                            ShipPhone = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "None",
                            OrderDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipAdsress = "351A Lạc Long Quân P5 Quận 11 TP.Hồ Chí Minh",
                            ShipEmail = "nqcuong720@gmail.com",
                            ShipPhone = "0377077630",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.PostEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnName("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnName("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnName("PostTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnName("Topic")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Mừng xuân, mừng đảng",
                            Image = "images/post/hinh.jpg",
                            PostTitle = "Khuyến mãi Tết Tân Sửu",
                            Status = 1,
                            TopicId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Mừng giáng sinh",
                            Image = "images/post/hinh.jpg",
                            PostTitle = "Lễ Giang Sinh",
                            Status = 1,
                            TopicId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Mừng khai trương",
                            Image = "images/post/hinh.jpg",
                            PostTitle = "Giảm giá 50%",
                            Status = 1,
                            TopicId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Siêu giảm giá !",
                            Image = "images/post/hinh.jpg",
                            PostTitle = "Black Friday",
                            Status = 1,
                            TopicId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Detail = "Ngày quốc tế phụ nữ",
                            Image = "images/post/hinh.jpg",
                            PostTitle = "Khuyễn mãi nhân ngày 8-3",
                            Status = 1,
                            TopicId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.ProductEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnName("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnName("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceSale")
                        .HasColumnName("PriceSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDetail")
                        .HasColumnName("ProductDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnName("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnName("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnName("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 480000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Áo thể thao nam Adidas",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 310000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Áo thể thao nữ Adidas",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 4,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 190000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Áo thể thao trẻ em Adidas",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 490000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Quần thể thao nam Adidas",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 2,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 390000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Quần thể thao nữ Adidas",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 190000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Quần thể thao trẻ em Adidas",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 940000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Giày thể thao - Nam ",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 3,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 510000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Guốc Juno",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 2,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 220000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Dép Bitis",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 4,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 790000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Áo khoác nam",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 3,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 19000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Tất nữ",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 690000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Áo khoác trẻ em Nike",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 850000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Quần tay công sở",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 3,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 1390000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Váy Elise",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 2,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "images/product/men/aokhoacadidas.jpg",
                            Price = 899000m,
                            PriceSale = 0m,
                            ProductDescription = "Áo thời trang mùa đông",
                            ProductName = "Giày Bitis Hunter X 2021",
                            Quantity = 150,
                            Status = 1,
                            SupplierId = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.RoleEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Access")
                        .HasColumnType("int");

                    b.Property<string>("AccessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Access = 0,
                            AccessName = "ADMIN",
                            Decription = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Access = 1,
                            AccessName = "Customer",
                            Decription = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Access = 2,
                            AccessName = "Sale",
                            Decription = "Sale"
                        },
                        new
                        {
                            Id = 4,
                            Access = 3,
                            AccessName = "Manager",
                            Decription = "Manager"
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.SlideEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SlideName")
                        .IsRequired()
                        .HasColumnName("SlideName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Slide");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 0,
                            SlideName = "Khuyễn mãi Noel",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 0,
                            SlideName = "Khuyễn mãi Ngày quốc tế Phụ nữ 8-3",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 0,
                            SlideName = "Khuyễn mãi Tết Tân Sửu",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 0,
                            SlideName = "Black Friday",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 0,
                            SlideName = "Ngày nhà giáo Việt Nam",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.SupplierEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnName("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SupplierName = "Bitis",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SupplierName = "Adidas",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SupplierName = "Juno",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SupplierName = "Elise",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.TopicEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orders")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnName("TopicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            TopicName = "Thời trang",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            TopicName = "Thời trang mùa đông",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            TopicName = "Thời trang mùa hè",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Orders = 0,
                            ParentId = 0,
                            Status = 1,
                            TopicName = "Thời trang Noel",
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CozaStore.Model.EntitiesModel.UserEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Access")
                        .HasColumnName("Access")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDay")
                        .HasColumnName("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirtName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnName("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Access = 0,
                            Address = "64 Cách Mạng Tháng 8 Phường 5 Quận 11 TP Hồ Chí Minh",
                            BirthDay = "2000-07-13",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqcuong720@gmail.com",
                            FirtName = "Cường",
                            LastName = "Nguyễn",
                            Password = "nqcuong720720",
                            Phone = "0377077630",
                            Sex = "Nam",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "nqcuong720"
                        },
                        new
                        {
                            Id = 2,
                            Access = 1,
                            Address = "128A An Dương Vương Phường 5 Quận 11 TP Hồ Chí Minh",
                            BirthDay = "2000-07-13",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqhai@gmail.com",
                            FirtName = "Hải",
                            LastName = "Nguyễn",
                            Password = "nqhai720720",
                            Phone = "0377077630",
                            Sex = "Nam",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "nqhai720"
                        },
                        new
                        {
                            Id = 3,
                            Access = 1,
                            Address = "280A Lạc Long Quân Phường 5 Quận 11 TP Hồ Chí Minh",
                            BirthDay = "2000-07-13",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqduy@gmail.com",
                            FirtName = "Duy",
                            LastName = "Nguyễn",
                            Password = "nqduy",
                            Phone = "0971561612",
                            Sex = "Nam",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "nqduy"
                        },
                        new
                        {
                            Id = 4,
                            Access = 2,
                            Address = "351A Lạc Long Quân Phường 5 Quận 11 TP Hồ Chí Minh",
                            BirthDay = "2000-07-13",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nqkhanh@gmail.com",
                            FirtName = "Khánh",
                            LastName = "Nguyễn",
                            Password = "nqkhanh",
                            Phone = "097123561",
                            Sex = "Nam",
                            Status = 1,
                            UpdateBy = 1,
                            UpdateDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "nqkhanh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
